export interface Country {
  code: string
  name: string
  emoji: string
}

export const COUNTRIES: Country[] = [
  { code: 'AU', name: 'Australia', emoji: '🇦🇺' },
  { code: 'AT', name: 'Austria', emoji: '🇦🇹' },
  { code: 'BE', name: 'Belgium', emoji: '🇧🇪' },
  { code: 'BR', name: 'Brazil', emoji: '🇧🇷' },
  { code: 'BG', name: 'Bulgaria', emoji: '🇧🇬' },
  { code: 'CA', name: 'Canada', emoji: '🇨🇦' },
  { code: 'CL', name: 'Chile', emoji: '🇨🇱' },
  { code: 'CN', name: 'China', emoji: '🇨🇳' },
  { code: 'CO', name: 'Colombia', emoji: '🇨🇴' },
  { code: 'HR', name: 'Croatia', emoji: '🇭🇷' },
  { code: 'CZ', name: 'Czech Republic', emoji: '🇨🇿' },
  { code: 'DK', name: 'Denmark', emoji: '🇩🇰' },
  { code: 'EG', name: 'Egypt', emoji: '🇪🇬' },
  { code: 'ET', name: 'Ethiopia', emoji: '🇪🇹' },
  { code: 'FI', name: 'Finland', emoji: '🇫🇮' },
  { code: 'FR', name: 'France', emoji: '🇫🇷' },
  { code: 'DE', name: 'Germany', emoji: '🇩🇪' },
  { code: 'GH', name: 'Ghana', emoji: '🇬🇭' },
  { code: 'GR', name: 'Greece', emoji: '🇬🇷' },
  { code: 'HK', name: 'Hong Kong', emoji: '🇭🇰' },
  { code: 'HU', name: 'Hungary', emoji: '🇭🇺' },
  { code: 'IN', name: 'India', emoji: '🇮🇳' },
  { code: 'ID', name: 'Indonesia', emoji: '🇮🇩' },
  { code: 'IE', name: 'Ireland', emoji: '🇮🇪' },
  { code: 'IL', name: 'Israel', emoji: '🇮🇱' },
  { code: 'IT', name: 'Italy', emoji: '🇮🇹' },
  { code: 'JP', name: 'Japan', emoji: '🇯🇵' },
  { code: 'KE', name: 'Kenya', emoji: '🇰🇪' },
  { code: 'KR', name: 'South Korea', emoji: '🇰🇷' },
  { code: 'KW', name: 'Kuwait', emoji: '🇰🇼' },
  { code: 'MY', name: 'Malaysia', emoji: '🇲🇾' },
  { code: 'MX', name: 'Mexico', emoji: '🇲🇽' },
  { code: 'MA', name: 'Morocco', emoji: '🇲🇦' },
  { code: 'NL', name: 'Netherlands', emoji: '🇳🇱' },
  { code: 'NZ', name: 'New Zealand', emoji: '🇳🇿' },
  { code: 'NG', name: 'Nigeria', emoji: '🇳🇬' },
  { code: 'NO', name: 'Norway', emoji: '🇳🇴' },
  { code: 'OM', name: 'Oman', emoji: '🇴🇲' },
  { code: 'PK', name: 'Pakistan', emoji: '🇵🇰' },
  { code: 'PE', name: 'Peru', emoji: '🇵🇪' },
  { code: 'PH', name: 'Philippines', emoji: '🇵🇭' },
  { code: 'PL', name: 'Poland', emoji: '🇵🇱' },
  { code: 'PT', name: 'Portugal', emoji: '🇵🇹' },
  { code: 'QA', name: 'Qatar', emoji: '🇶🇦' },
  { code: 'RO', name: 'Romania', emoji: '🇷🇴' },
  { code: 'SA', name: 'Saudi Arabia', emoji: '🇸🇦' },
  { code: 'SG', name: 'Singapore', emoji: '🇸🇬' },
  { code: 'ZA', name: 'South Africa', emoji: '🇿🇦' },
  { code: 'ES', name: 'Spain', emoji: '🇪🇸' },
  { code: 'LK', name: 'Sri Lanka', emoji: '🇱🇰' },
  { code: 'SE', name: 'Sweden', emoji: '🇸🇪' },
  { code: 'CH', name: 'Switzerland', emoji: '🇨🇭' },
  { code: 'TW', name: 'Taiwan', emoji: '🇹🇼' },
  { code: 'TZ', name: 'Tanzania', emoji: '🇹🇿' },
  { code: 'TH', name: 'Thailand', emoji: '🇹🇭' },
  { code: 'TR', name: 'Turkey', emoji: '🇹🇷' },
  { code: 'AE', name: 'United Arab Emirates', emoji: '🇦🇪' },
  { code: 'GB', name: 'United Kingdom', emoji: '🇬🇧' },
  { code: 'US', name: 'United States', emoji: '🇺🇸' },
  { code: 'UY', name: 'Uruguay', emoji: '🇺🇾' },
  { code: 'UG', name: 'Uganda', emoji: '🇺🇬' },
  { code: 'VN', name: 'Vietnam', emoji: '🇻🇳' },
]

export function getCountryByCode(code: string): Country | undefined {
  return COUNTRIES.find((c) => c.code === code)
}
