// Hardcoded exchange rates: local units per 1 USD
// Updated periodically — not live rates
export const EXCHANGE_RATES: Record<string, number> = {
  USD: 1.0,
  GBP: 0.79,
  EUR: 0.92,
  AUD: 1.53,
  CAD: 1.36,
  CHF: 0.89,
  SEK: 10.4,
  NOK: 10.6,
  AED: 3.67,
  SGD: 1.34,
  BRL: 5.05,
  MXN: 17.2,
  ZAR: 18.5,
  INR: 83.5,
  NGN: 1600,
  JPY: 149.0,
  KRW: 1330,
  NZD: 1.63,
  CNY: 7.24,
  HKD: 7.82,
  DKK: 6.87,
  PLN: 4.02,
  CZK: 22.9,
  HUF: 363,
  RON: 4.58,
  BGN: 1.8,
  HRK: 6.95,
  TRY: 32.1,
  ILS: 3.76,
  SAR: 3.75,
  QAR: 3.64,
  KWD: 0.31,
  BHD: 0.38,
  OMR: 0.38,
  EGP: 30.9,
  MAD: 10.0,
  KES: 129,
  GHS: 15.8,
  TZS: 2530,
  UGX: 3760,
  ETB: 56.5,
  PKR: 278,
  BDT: 110,
  LKR: 308,
  THB: 34.2,
  VND: 24300,
  IDR: 15650,
  PHP: 55.9,
  MYR: 4.71,
  TWD: 31.5,
  CLP: 945,
  COP: 3950,
  PEN: 3.73,
  ARS: 842,
  UYU: 39.2,
}

// ISO 3166-1 alpha-2 country code → ISO 4217 currency code
export const COUNTRY_CURRENCY: Record<string, string> = {
  US: 'USD',
  GB: 'GBP',
  AU: 'AUD',
  CA: 'CAD',
  DE: 'EUR',
  FR: 'EUR',
  NL: 'EUR',
  BE: 'EUR',
  AT: 'EUR',
  ES: 'EUR',
  IT: 'EUR',
  PT: 'EUR',
  FI: 'EUR',
  IE: 'EUR',
  GR: 'EUR',
  SE: 'SEK',
  NO: 'NOK',
  DK: 'DKK',
  CH: 'CHF',
  AE: 'AED',
  SG: 'SGD',
  BR: 'BRL',
  MX: 'MXN',
  ZA: 'ZAR',
  IN: 'INR',
  NG: 'NGN',
  JP: 'JPY',
  KR: 'KRW',
  NZ: 'NZD',
  CN: 'CNY',
  HK: 'HKD',
  PL: 'PLN',
  CZ: 'CZK',
  HU: 'HUF',
  RO: 'RON',
  BG: 'BGN',
  HR: 'EUR',
  TR: 'TRY',
  IL: 'ILS',
  SA: 'SAR',
  QA: 'QAR',
  KW: 'KWD',
  BH: 'BHD',
  OM: 'OMR',
  EG: 'EGP',
  MA: 'MAD',
  KE: 'KES',
  GH: 'GHS',
  TZ: 'TZS',
  UG: 'UGX',
  ET: 'ETB',
  PK: 'PKR',
  BD: 'BDT',
  LK: 'LKR',
  TH: 'THB',
  VN: 'VND',
  ID: 'IDR',
  PH: 'PHP',
  MY: 'MYR',
  TW: 'TWD',
  CL: 'CLP',
  CO: 'COP',
  PE: 'PEN',
  AR: 'ARS',
  UY: 'UYU',
}

export function getCurrencyForCountry(countryCode: string): string {
  return COUNTRY_CURRENCY[countryCode] ?? 'USD'
}

export function getExchangeRate(currency: string): number {
  return EXCHANGE_RATES[currency] ?? 1.0
}

export function displayPrice(usdCents: number, currency: string): string {
  if (usdCents === 0) return '—'
  const rate = getExchangeRate(currency)
  const localAmount = (usdCents / 100) * rate
  try {
    return new Intl.NumberFormat('en-US', {
      style: 'currency',
      currency,
      minimumFractionDigits: 0,
      maximumFractionDigits: 0,
    }).format(localAmount)
  } catch {
    return `${currency} ${Math.round(localAmount).toLocaleString()}`
  }
}
